# **Comprehensive NLP Lab: From Preprocessing to Feature Extraction**

In this lab, you will explore a wide range of Natural Language Processing (NLP) techniques, from basic text preprocessing to advanced feature extraction and analysis. By the end of this lab, you will be able to:

1. **Tokenize** and preprocess text data.
2. Remove **stop words** and **punctuation**.
3. Apply **stemming** and **lemmatization**.
4. Extract features using **Bag of Words (BoW)** and **TF-IDF**.
5. Generate **n-grams** to capture contextual information.
6. Evaluate the impact of different preprocessing techniques on text data.

Let's dive in!

## **1. Setup the Environment**

Now, import the required libraries:

## **2. Text Preprocessing**

### **Exercise 1: Tokenization and Stop Word Removal**

Tokenize the following text

In [1]:
# ------------------------------------------------------------------ #
#                 Tokenization de chaîne de caractère                #
# ------------------------------------------------------------------ #

from nltk.tokenize import word_tokenize # Import

text = "Natural Language Processing (NLP) is a fascinating field of study! It involves analyzing and understanding human language."
tokenized_text = word_tokenize(text=text, language="english", preserve_line=False)

# preserve_line=False pour découper en phrases propres. ex. Texte long, multi-paragraphes
# preserve_line=True pour garder la structure sans segmentation automatique. ex. Prétraitement brut de données avant NLP avancé

print(tokenized_text)

['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'fascinating', 'field', 'of', 'study', '!', 'It', 'involves', 'analyzing', 'and', 'understanding', 'human', 'language', '.']

Remove stop words and store the result in a variable called `filtered_tokens`

In [2]:
# ------------------------------------------------------------------ #
#                    Mots de liaison + ponctuation                   #
# ------------------------------------------------------------------ #

# Import de la liste des stopwords en anglais
from nltk.corpus import stopwords

# Définir la liste des stopwords anglais une fois
stop_words = set(stopwords.words('english'))

# Conversion en lowercase + removal ponctuation
def to_lowercase_no_punct(tokens):
  return [word.lower() for word in tokens if word.isalpha()]

# Fonction pour enlever les stopwords sans perdre l’ordre
def remove_sw(tokens):
    return [word for word in tokens if word.lower() not in stop_words]

# Application sur tokenized_text
tokenized_text_to_lowercase = to_lowercase_no_punct(tokenized_text)
filtered_tokens = remove_sw(tokenized_text_to_lowercase)

print(filtered_tokens)

['natural', 'language', 'processing', 'nlp', 'fascinating', 'field', 'study', 'involves', 'analyzing', 'understanding', 'human', 'language']

### **Exercise 2: Stemming and Lemmatization**

Apply stemming and lemmatization to the `filtered_tokens`. Compare the results.

Apply stemming and store the result in `stemmed_tokens`

In [3]:
# ------------------------------------------------------------------ #
#                            Stemming data                           #
# ------------------------------------------------------------------ #

# Import stemmer
from nltk.stem import PorterStemmer

# Instanciate
stemmer = PorterStemmer()

# Fonction pour stemmatiser
def stemmatize(tokens):
    return [stemmer.stem(word) for word in tokens]

# Application
stemmed_tokens = stemmatize(filtered_tokens)

print("Stemmed Tokens:", stemmed_tokens)

Stemmed Tokens: ['natur', 'languag', 'process', 'nlp', 'fascin', 'field', 'studi', 'involv', 'analyz', 'understand', 'human', 'languag']

Apply lemmatization and store the result in `lemmatized_tokens`

In [4]:
# ------------------------------------------------------------------ #
#                          Lemmatizing data                          #
# ------------------------------------------------------------------ #

# Import stemmer
from nltk.stem import WordNetLemmatizer

# Instanciate
lemmatizer = WordNetLemmatizer()

# Fonction pour stemmatiser
def lemmatize(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

# Application
lemmatized_tokens = lemmatize(filtered_tokens)

print("Lemmatized Tokens:", lemmatized_tokens)

Lemmatized Tokens: ['natural', 'language', 'processing', 'nlp', 'fascinating', 'field', 'study', 'involves', 'analyzing', 'understanding', 'human', 'language']

## **3. Feature Extraction**

### **Exercise 3: Bag of Words (BoW)**

Use the `CountVectorizer` from `scikit-learn` to create a Bag of Words representation of the following corpus

In [5]:
# ------------------------------------------------------------------ #
#                      Création de Bag of Words                      #
# ------------------------------------------------------------------ #

from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "I love NLP.",
    "NLP is amazing.",
    "I enjoy learning new things in NLP."
]

# Initialisation de CountVectorizer
bow_vect = CountVectorizer(max_features=1000) # most common 1000 words

# Fit and transform the corpus into a BoW representation
X = bow_vect.fit_transform(corpus)

print("Bag of Words:\n", X.toarray())
print("Vocabulary:", bow_vect.get_feature_names_out())

Bag of Words:
 [[0 0 0 0 0 1 0 1 0]
 [1 0 0 1 0 0 0 1 0]
 [0 1 1 0 1 0 1 1 1]]
Vocabulary: ['amazing' 'enjoy' 'in' 'is' 'learning' 'love' 'new' 'nlp' 'things']

### **Exercise 4: TF-IDF**

Use the `TfidfVectorizer` from `scikit-learn` to create a TF-IDF representation of the same corpus. Store the result in `X_tfidf`

In [6]:
# ------------------------------------------------------------------ #
#                               TF-IDF                               #
# ------------------------------------------------------------------ #

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import pandas as pd

corpus = ["I love NLP.", "NLP is amazing.", "I enjoy learning new things in NLP."]

# BoW to count the words
bow_vect = CountVectorizer(min_df=1) # min_df=1 : on garde tous les mots présents au moins 1 fois
term_freq_matrix = bow_vect.fit_transform(corpus) # Matrix BoW

# Initialisation transformeur TF-IDF
X_tfidf = TfidfTransformer(norm="l2") # norm="l2" : normalise les vecteurs pour éviter que les longues phrases dominent
X_tfidf.fit(term_freq_matrix) # Fit du TF-IDF
tf_idf_matrix = X_tfidf.transform(term_freq_matrix) # Transforme la matrice de fréq en pondération TF-IDF

# Checks
print("Vocabulary:", bow_vect.vocabulary_, '\n') # Affiche le vocalubary généré avec index
print(tf_idf_matrix.todense()) # Affiche TF-IDF matrix

# Data Viz => associe chaque mot à son poids IDF
df_idf = pd.DataFrame(X_tfidf.idf_, index=bow_vect.get_feature_names_out(), columns=["idf_weights"])
df_idf.sort_values(by=['idf_weights']) # Tri fréquence croissant

Vocabulary: {'love': 5, 'nlp': 7, 'is': 3, 'amazing': 0, 'enjoy': 1, 'learning': 4, 'new': 6, 'things': 8, 'in': 2}

[[0.         0.         0.         0.         0.         0.861037
  0.         0.50854232 0.        ]
 [0.65249088 0.         0.         0.65249088 0.         0.
  0.         0.38537163 0.        ]
 [0.         0.43238509 0.43238509 0.         0.43238509 0.
  0.43238509 0.2553736  0.43238509]]

          idf_weights
nlp          1.000000
amazing      1.693147
enjoy        1.693147
in           1.693147
is           1.693147
learning     1.693147
love         1.693147
new          1.693147
things       1.693147

### **Exercise 5: N-grams**

Generate `bigrams (2-grams)` from the corpus using `CountVectorizer`. Store the result in `X_bigram`

In [7]:
# ------------------------------------------------------------------ #
#                         Création de Bigrams                        #
# ------------------------------------------------------------------ #

from sklearn.feature_extraction.text import CountVectorizer

corpus = ["I love NLP.", "NLP is amazing.", "I enjoy learning new things in NLP."]

# Initialisation de CountVectorizer
bigram_vectorizer = CountVectorizer(max_features=1000, ngram_range=(2, 2)) # most common 1000 words, ngram_range=(2, 2) from 1 mot seul to 2 mots

# Fit and transform the corpus into a Bigrams representation
X_bigram = bigram_vectorizer.fit_transform(corpus)

print("Bigrams:\n", X_bigram.toarray())
print("Bigrams Vocabulary:", bigram_vectorizer.get_feature_names_out())

Bigrams:
 [[0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0]
 [1 1 0 1 0 1 0 1]]
Bigrams Vocabulary: ['enjoy learning' 'in nlp' 'is amazing' 'learning new' 'love nlp'
 'new things' 'nlp is' 'things in']

## **4. Advanced Exercise: Custom Preprocessing Pipeline**

### **Exercise 6: Build a Custom Preprocessing Pipeline**

Combine all the preprocessing steps (tokenization, stop word removal, punctuation removal, stemming/lemmatization) into a single function.

In [31]:
%pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 1.8 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: six in /Users/joachimjasmin/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (pyproject.toml) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993331 sha256=2f5526007c8ee866fd2f9edb64aa287ecf6b45eed41224b1230746d0da44cc3e
  Stored in directory: /Users/joachimjasmin/Library/Caches/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer, PorterStemmer, SnowballStemmer
from nltk import pos_tag
from langdetect import detect

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    return wordnet.NOUN

def text_preprocessing_pipeline(text: str, operation: str = "lemmatize"):
    """
    Pipeline de prétraitement de texte :
    - Détection automatique de langue
    - Tokenisation
    - Nettoyage : stopwords, ponctuation, minuscule
    - Normalisation : stemming ou lemmatisation
    """

    # Langues disponibles dans NLTK
    NLTK_LANGUAGES = set(stopwords.fileids())

    # Correspondance ISO langdetect → nom stopwords
    ISO_TO_NLTK = {
        'ar': 'arabic',
        'az': 'azerbaijani',
        'bn': 'bengali',
        'ca': 'catalan',
        'zh-cn': 'chinese',
        'zh-tw': 'chinese',
        'da': 'danish',
        'nl': 'dutch',
        'en': 'english',
        'fi': 'finnish',
        'fr': 'french',
        'de': 'german',
        'el': 'greek',
        'he': 'hebrew',
        'hi': 'hinglish',
        'hu': 'hungarian',
        'id': 'indonesian',
        'it': 'italian',
        'kk': 'kazakh',
        'ne': 'nepali',
        'no': 'norwegian',
        'pt': 'portuguese',
        'ro': 'romanian',
        'ru': 'russian',
        'sl': 'slovene',
        'es': 'spanish',
        'sv': 'swedish',
        'ta': 'tamil',
        'tr': 'turkish',
        'tg': 'tajik',
    }

    # Détection langue
    lang_code = detect(text)
    language = ISO_TO_NLTK.get(lang_code, 'english')

    if language not in NLTK_LANGUAGES:
        print(f"[INFO] Stopwords for '{language}' not found. Fallback to English.")
        language = 'english'

    # Tokenisation
    tokens = word_tokenize(text, language="english") # toujours en anglais

    # Nettoyage
    stop_words = set(stopwords.words(language))
    tokens = [word.lower() for word in tokens if word.isalpha() and word.lower() not in stop_words]

    # Normalisation
    if operation == "porter":
        return [PorterStemmer().stem(word) for word in tokens]

    elif operation == "snowball":
        return [SnowballStemmer(language).stem(word) for word in tokens]

    elif operation == "lemmatize":
        if language != "english":
            return tokens
        lemmatizer = WordNetLemmatizer()
        tagged = pos_tag(tokens)
        return [lemmatizer.lemmatize(word, get_wordnet_pos(pos)) for word, pos in tagged]

    else:
        raise ValueError("operation must be 'porter', 'snowball', or 'lemmatize'")

Apply this function to the following text

In [71]:
text = "Natural Language Processing (NLP) is a fascinating field of study! It involves analyzing and understanding human language."
processed_text = text_preprocessing_pipeline(text, "lemmatize")

In [72]:
print("Processed Text:", processed_text)

Processed Text: ['natural', 'language', 'processing', 'nlp', 'fascinating', 'field', 'study', 'involve', 'analyze', 'understand', 'human', 'language']

## **5. Evaluation of Preprocessing Techniques**

### **Exercise 7: Compare Preprocessing Techniques**

Compare the results of stemming and lemmatization on the following sentence. Store the results in `stemmed_tokens` and `lemmatized_tokens`

In [44]:
sentence = "The cats are playing with the mice in the garden."

stemmed_tokens = text_preprocessing_pipeline(sentence, "porter")
lemmatized_tokens = text_preprocessing_pipeline(sentence, "lemmatize")

In [45]:
print("Original Tokens:", filtered_tokens)
print("Stemmed Tokens:", stemmed_tokens)
print("Lemmatized Tokens:", lemmatized_tokens)

Original Tokens: ['natural', 'language', 'processing', 'nlp', 'fascinating', 'field', 'study', 'involves', 'analyzing', 'understanding', 'human', 'language']
Stemmed Tokens: ['cat', 'play', 'mice', 'garden']
Lemmatized Tokens: ['cat', 'play', 'mouse', 'garden']

## **6. Real-World Dataset: Sentiment Analysis**

### **Exercise 8: Preprocess and Analyze Tweets**

In this exercise, you will work with a real-world dataset of tweets. The dataset contains 5000 positive and 5000 negative tweets. Your task is to preprocess the tweets and extract features for sentiment analysis.

In [46]:
import nltk
nltk.download('twitter_samples')

[nltk_data] Downloading package twitter_samples to
[nltk_data]     /Users/joachimjasmin/nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!

True

In [47]:
# Load the dataset
from nltk.corpus import twitter_samples

Load the dataset of positive and negative tweets.

In [48]:
positive_tweets = twitter_samples.strings('positive_tweets.json')
negative_tweets = twitter_samples.strings('negative_tweets.json')

Combine them into a single list called ``all_tweets`` and create a corresponding list of labels called `labels`.

In [57]:
# your code here
all_tweets = positive_tweets + negative_tweets
labels = ["pos" for _ in positive_tweets] + ["neg" for _ in negative_tweets]

In [58]:
# Print a sample tweet
print("Sample Tweet:", all_tweets[0])
print("Label:", labels[0])

Sample Tweet: #FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)
Label: pos

### **Exercise 9: Preprocess Tweets**

Apply the custom preprocessing pipeline to the entire dataset of tweets. Store the result in ``preprocessed_tweets``.

In [83]:
print(all_tweets)

['#FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)', '@Lamb2ja Hey James! How odd :/ Please call our Contact Centre on 02392441234 and we will be able to assist you :) Many thanks!', '@DespiteOfficial we had a listen last night :) As You Bleed is an amazing track. When are you in Scotland?!', '@97sides CONGRATS :)', 'yeaaaah yippppy!!!  my accnt verified rqst has succeed got a blue tick mark on my fb profile :) in 15 days', '@BhaktisBanter @PallaviRuhail This one is irresistible :)\n#FlipkartFashionFriday http://t.co/EbZ0L2VENM', "We don't like to keep our lovely customers waiting for long! We hope you enjoy! Happy Friday! - LWWF :) https://t.co/smyYriipxI", '@Impatientraider On second thought, there’s just not enough time for a DD :) But new shorts entering system. Sheep must be buying.', 'Jgh , but we have to go to Bayan :D bye', 'As an act of mischievousness, am calling the ETL layer of our in-house warehousing app Katamari.\n\nWell… as the name implies :p.', '#FollowFriday @wncer1 @Defense_gouv for being top influencers in my community this week :)', "Who Wouldn't Love These Big....Juicy....Selfies :) - http://t.co/QVzjgd1uFo http://t.co/oWBL11eQRY", '@Mish23615351  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', "@jjulieredburn Perfect, so you already know what's waiting for you :)", 'Great new opportunity for junior triathletes aged 12 and 13 at the Gatorade series! Get your entries in :) http://t.co/of3DyOzML0', 'Laying out a greetings card range for print today - love my job :-)', "Friend's lunch... yummmm :)\n#Nostalgia #TBS #KU.", "@RookieSenpai @arcadester it is the id conflict thanks for the help :D here's the screenshot of it working", '@oohdawg_ Hi liv :))', 'Hello I need to know something can u fm me on Twitter?? — sure thing :) dm me x http://t.co/W6Dy130BV7', '#FollowFriday @MBandScott_ @Eric_FLE @pointsolutions3 for being top new followers in my community this week :)', "@rossbreadmore I've heard the Four Seasons is pretty dope. Penthouse, obvs #Gobigorgohome\nHave fun y'all :)", '@gculloty87 Yeah I suppose she was lol! Chat in a bit just off out x :))', 'Hello :) Get Youth Job Opportunities follow &gt;&gt; @tolajobjobs @maphisa301', "💅🏽💋 - :)))) haven't seen you in years", '@Bosslogic @amellywood @CW_Arrow @ARROWwriters Thank you! :-)', '@johngutierrez1 hope the rest of your night goes by quickly... I am off to bed... got my music fix and now it is time to dream  :)', 'Spiritual Ritual Festival (Népal)\nBeginning of Line-up :)\nIt is left for the line-up (y)\nSee more at:... http://t.co/QMNz62OEuc', "@ke7zum Hey Sarah! Send us an email at bitsy@bitdefender.com and we'll help you asap :)", '@izzkamilhalda lols. :D', 'MY kik - hatessuce32429 #kik #kikme #lgbt #tinder #nsfw #akua #cumshot :) http://t.co/TnHJD36yzf', '@KalinWhite come to my house :)))))', '#nsn_supplements, Effective press release distribution with results! :) [link removed] #PressRelease #NewsDistribution', 'Hi BAM ! @BarsAndMelody \nCan you follow my bestfriend @969Horan696 ? \nShe loves you a lot :) \nSee you in Warsaw &lt;3 \nLove you &lt;3 x46', 'everyone watch the documentary Earthlings on YouTube :-)', '@jamiefigsxx  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', '#FollowFriday @MichelBauza @InvataOnline for being top supports in my community this week :)', 'buuuuuuuut oh well :-)', '@leisuremarkltd @NoshandQuaff @aktarislam @keanebrands @HeritageSilver I am looking forward to visiting next week #letsgetmessy Jo :-)', '@sehunshinedaily if it makes u feel better i never have nor will see anyone in kpop in the flesh :D', '@Joyster2012 @CathStaincliffe Good for you, girl!! Best wishes :-)', '@_Kimimi A great enough reason to listen to one epic soundtrack. :D', '@AquaDesignGroup Thank you for the shout out. Have a great Friday :)', 'I added a video to a @YouTube playlist http://t.co/yzpfsMxUq0 im back on twitch and today it going to be league :) - 1 / 4', 'Would love to see you dear in #Jordan :) waiting you! @FIRDOZ  :) @VisitJordan @dannyprol', '@ABNORMAL_ANA92 oh, okay :D thanks!', '@sssniperwolf like how to fake gameplays ;) haha Im kidding, im kidding. You do good stuff :).', '@dennislami @Dicle_Aygur, yeah exactly :)', 'Our new product line is in our #etsy shop now! Check it out :) http://t.co/h8exCTLQxg #boxroomcrafts', '@PeakYourMind I hope your vacation is going great! :D', '@groovinshawn they are rechargeable and it normally comes with a charger when u buy it :)', '#FollowFriday @France_Espana @reglisse_menthe @CCI_inter for being top engaged members in my community this week :)', "Well she's asleep and I have no one to talk to sooo someone text me :)", "@brynybrath @smallcappy Yes, I suppose. I bet he'll have a blue fit after hearing her speech today. Pity :-)", 'Green gardens, midnight sun, beautiful canals dasvidaniya till next visit.:)', '@KeithRParsons are you scouting SG for a future WLAN pros conference here in Asia? :)', '@Cecilie_Hell @420evilangel @wazimotometal @durooooooo @spigranty Good for u, better change it to lollipop 🍭 :).', 'We &lt;3 u Nez :) #AGNEZMO https://t.co/cGViMHSINz', '@LittleMix Follow me Please :)  This is my Big Dream :)', '@Elemaaan  oley be :D', '"@CowokAddict: Mama is the only reason why I stand stronger up to now! :)"', '@MacatangayApril  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', '@tk_kjk_kndr @boukendreamer OH MY GOD MISTY, MY BABY IS SO CUTE!!! :D', '@BhaktisBanter \n\nI love blue :)\n#FlipkartFashionFriday http://t.co/HnbinH35ES', "@CarcassDrop Woohoo! Can't wait :) Have you signed up yet, or still thinking about it? MKa", 'i have liam access now :))', '@SyuhxdxTengku most welcome :)', 'Stats for the day have arrived. 1 new follower and NO unfollowers :) via http://t.co/p6K6SiH58a.', "@sluttywife2 you shouldn't be surprised...you have an amazing figure :)", '#FollowFriday @murtishaw @aqui_fr @FRTechStartups for being top influencers in my community this week :)', '#HappyBirthdayEmilyBett @emilybett :) Wishing you all the best you beautiful,sweet,talented,amazing… https://t.co/humtC1tr3I', '2 plans for the day down the drain great :):', '@x123456789tine @5SOS_FAHUpdates gotta love timezones :p', 'are your parents proud of you — lol, not in the least :D maybe sometimes they get happy because of my grades, al... http://t.co/bJjeGIOOGU', 'Grande :)  https://t.co/gsaaxNpR8u', 'Manila_bro has chosen to follow me on Twitter! http://t.co/lKXZWXN1fb. Thanks for the follow :)', "@syazwanzainal sure let me know when you're around..at this side of the world #eh u too take care :-)", '#FollowFriday @michae1green @superninjaalan @Doug_Laney for being top new followers in my community this week :)', 'finally the fucking weekend :)', 'REAL :)', '@LoLEsportspedia thanks :D', 'Hi BAM ! @BarsAndMelody \nCan you follow my bestfriend @969Horan696 ? \nShe loves you a lot :) \nSee you in Warsaw &lt;3 \nLove you &lt;3 x45', 'YES! I Joined #HushedCallWithFraydoe for a call &amp; gift from @_Fraydoe &lt;3 Gotta Get @HushedApp :D http://t.co/VaLVe8omdT', '@YasLarry yeahhh :)', 'can I DM you &amp; make your night better :)))', 'just joined the #HushedPinWithSammy Event :D Might get to Text with @SammyWilk for a day! Luv U @HushedApp http://t.co/kGfgawdHy9', 'Would really appreciate it if you share this video around :) https://t.co/MhK3B3wOpQ', 'Hello :) Get Youth Job Opportunities follow &gt;&gt; @tolajobjobs @xhebenkewu_9920', '@TomParker oh wow!! That is beautiful tom :)', 'Love You @darlingIXHAI22 @SyreenAnne :)) https://t.co/wx7yRrE7sV', 'I added a video to a @YouTube playlist http://t.co/HVVPhSYakA im back on twitch and today it going to be league :) - 1 / 3', '#FollowFriday @AmericanOGrain @PecomeP @APaulicand for being top supports in my community this week :)', '@ZaynZaynmalik30  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', "Gym Monday can't wait :). Likes", "@HarNiLiZaLouis Hey, here's your invite to join Scope as an influencer :)  http://t.co/rZgZtQ2fJT", 'Those friends know themselves :)', 'waiting for nudes :-)', '@JacobWhitesides go sleep u ! :)))))))))', 'Stats for the day have arrived. 1 new follower and NO unfollowers :) via http://t.co/RB8pMNgMEo.', 'My birthday is a week today! :D', "@metalgear_jp @Kojima_Hideo I want you're T-shirts ! They are so cool ! :D", '@AxeRade haw phela if am not looking like Mom obviously am looking like him :)', '@zaynmalik prince charming on stage :) x https://t.co/OnVFhzt5fZ', 'i have really good luck :)', 'Stats for the day have arrived. 1 new follower and NO unfollowers :) via http://t.co/XzsOGaC4zK.', '#FollowFriday @straz_das @DCarsonCPA @GH813600 for being top engaged members in my community this week :)', '@twentyonepilots @fujirock_jp tylers hipster glasses :D', '@MartyRafenstein \n\nHey Marty !! Glad to see on Twitter. :)', '@UKBusinessLunch Hi we will be joining you again today :)', '@LAfitnessUKhelp done thanks :-)', 'Its already afternoon, lets read Al Kahfi before the day finish :)', 'OhmyG! yaya dub @mainedcm im done doing to stalk your ig accnt.. GONDOOO MOO TOLOGOOO :) HAHA', "@rozbabes Here's your invite to become a Scope influencer :) Details here: http://t.co/ipJ2yOiGet", '#FollowFriday @NGourd @Locita @D_Robert_Kelly for being top influencers in my community this week :)', '@kevinthewhippet @Cassie_Spaniel @Bracken_Nelson @BellisimoBella1 @SpanielHarry thanks :) zzz xx', 'Physiotherapy Friday is my hashtag for today. Custom! :-)', '@Cjlopez21 you know I will 💪 Monica and I miss you to, yeah sounds good to me :)', '"Good morning, beautiful :)" That\'s all it takes.', 'Hi BAM ! @BarsAndMelody \nCan you follow my bestfriend @969Horan696 ? \nShe loves you a lot :) \nSee you in Warsaw &lt;3 \nLove you &lt;3 x43', '@MandaScapinello oh yeah?? I am definitely going to try it tonight then! :) we took your advice too! We are in Treviso now!', '@morallosanthony  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', "@NIKKIERIOZZI Hi! Would you like an @imPastel concert? Let me know your city and country and I'll start working on it! Thanks :)", 'Fine, \n...Have a gorgeous Friday, friend!!..; xo..-:)) https://t.co/JmpkZP2DaI', 'Oven roasted garlic in olive oil, sun dried tomatoes, some dried basil, and century tuna :) https://t.co/EsCc9QhLob', '@HostMyOffice @NigelPWhittaker @lemezma @TWBC_Business @_TheBunkerJL Right back atchya!  Have a great day everyone :)', "@TeamTall17 @FlashHayer  but doesn't even follow back :-)", 'The future is almost here then :) https://t.co/rolE3ZCL97', '#FollowFriday @Michelploria @MyFrenchCity @jasoncreation for being top new followers in my community this week :)', 'No chance :)', '@ChiAB2486 @MrCliveC @PCDKirkwood @DC_ARVSgt @COPS_President @EmWilliamsCCCU @LauraRGallagher @Hall11Kate @LaMinx541 @JohnTarbet71 cheers :)', '@thatguycalledP go po for ice cream :))', '@19strawberry66 I agree 100% :)', '@SpazzyTsukihara hehehehe thats the point :p', '@KalinWhite next time just stay home :)', '@Gculloty87 thanks :)', '#FollowFriday @digitalplace2be @intlboost @_lafontpresse for being top supports in my community this week :)', '@stayfaboo it will be up soon, i promise :)', 'Web Whatsapp volta a funcionar com iPhone jailbroken. :-)', '@crustyolddeen (I plan on watching it later) at 34 mins Leia appears as a hologram from R2D2 w a message for Obi Wan as he sits w Luke :)', '@Mburu__ Inter 3 UCL, Arsenal... Small team, Right! :)', 'Just passing by :) 🚂 (@ Dewsbury Railway Station (DEW) - @nationalrailenq in Dewsbury, West Yorkshire) https://t.co/DvBssHbrfx', '@ClearlyArticle :) its 430 am smh', "@uptommosass it's 9:25 am here :) I live in Scotland :) it's strange to imagine what?- Megan xx", '@bookmyshow \n\n !\n#MasaanToday\n#MasaanToday\n\nA4.... Shweta Tripathi  \n !\n#MasaanToday\n#MasaanToday\n\n-.:-) .-..,', '@WforWoman 5. Over 20 W kurtas! And my Mom has about half the number I have :D #WSaleLove', 'Ah! Hello back Larry! @TransworldBooks :) https://t.co/8XhjJb4jtH', 'Anyway my Friday is looking kinda gooood :)', '@jhun_hunyo  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', "Lol. Well. That's life :) thank God it enn you  https://t.co/GLoCEIjGQQ", '@OJBJ @holmesjsamuel surely this could be your warmup this morning ??? Coming on 15th to Bath :) xx', "Dum Dum Andar - Ram Sampath, Sona Mohapatra &amp; Samantha Edwards Mein Tulane to razi razi, Wah! That's Josh :) http://t.co/ul8MARDfhm", '@justinbieber :) always smile', '@darlakim_ picture. :)', "@arsenalnewsasit Thanks again, your time 16.20 right? That's perfect timing for me here :).", '#FollowFriday @IzywayLesExpats @na4innov @InXpressCoAzur for being top engaged members in my community this week :)', '@Juleeyaanaa i know :))', '#GiveItUp We have already given up our gas subsidy long back when this initiative was proposed.. Feeling so delighted having done that!! :)', '@dayloladay I missed this yesterday!! :-)', 'Hi BAM ! @BarsAndMelody \nCan you follow my bestfriend @969Horan696 ? \nShe loves you a lot :) \nSee you in Warsaw &lt;3 \nLove you &lt;3 x42', '@jaimeemelanie_ lmaoo! The best songs ever &lt;3 We shall have our own little throwback this week (y) :p', '@Clazziebritchas then go to the outlying islands, such as Cheung Chau, Mui Wo....totally different :))', "#KFCkitchentours Kitchen is so clean. I'm totally amazed :) @KFC_India", '@cybelxxx  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', '@Jana7380 on the cusp of testing the waters, hope yours is rewarding :)', '#FollowFriday @BroadcastBeat @InSunWeTrust @conseilsmkg for being top influencers in my community this week :)', "arummzz: Let's go... I'll drive for you :p\n\n#traveling #traveler #yogyakarta #jeep #Indonesia #instamood… https://t.co/s7y4Ys5JeU", 'Anyone wanna skype me? :D', '@agylyxa may i look so, bit i am a real nice friendly girl :-)', 'Im not like them. But i can pretend~ :)', 'watching where we are concert film :)', "Congratulations @amisharanka95, you're the winner to our #CheesyDelights contest :)\nPlease DM us your address and contact number!", ':) Have a great weekend guys! https://t.co/DLDKLpeTAb', '#FollowFriday @CLARAROJASG @BF_P2C @MyBusiness_Plan for being top new followers in my community this week :)', '@PuaMagasiva it was cool seeing you film today! :)', "Check out Email Marketing 24/7:  http://t.co/O5fjR7oEqk you won't regret if you buy it :)", '@vineshpomal LOL. Come join us ... See u in around 14 hours if u leave now, without delays. :)', "Actually very easy doing like this, it must be a station I guess where the train 'wd take at least an hour for shifting its engine etc :-)", 'sunburn is peeling :-)', '@Sexdate_gratis Visit my blog http://t.co/UzOAqroWKx thanks :D', "@TikoSD Hi! Would you like an @imPastel concert? Let me know your city and country and I'll start working on it! Thanks :)", '@no1_razorstan then talk to me. I can help you :)', '"@CassTheTrainer: A Huge &amp; Warm Welcome to @VodkaBlond :-))"\n\n☆ finally we complete the triangle ! ☆', '@LucienneDiver I live in Northern Ireland. :) what sights have you seen?', '@Mecastor01Mica  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', '#FollowFriday @Z_Intl_Agency @Tivipro @compexly for being top supports in my community this week :)', 'Stats for the day have arrived. 1 new follower and NO unfollowers :) via http://t.co/6prugvmOuC.', '@imraina feeling smthng smthng fr u...lol...wanna hug u....XOXO...love uu jaann take care :* :)) &lt;3 :")', 'thanks mom :)', 'Thanks #TopNewFollowers @BestOfFicPad @MrCFluegel @JeanMarcPN Happy to connect :)', "@MooseAllain @MeatBingo that is the just most wonderful thing, it's made me feel all fluffy inside. Great pirouette, Moose :D", "@KristophCajon I have a trip to philly in December so after that :) I'd love to come out there dude.", 'Hi BAM ! @BarsAndMelody \nCan you follow my bestfriend @969Horan696 ? \nShe loves you a lot :) \nSee you in Warsaw &lt;3 \nLove you &lt;3 x41', "The question is flawed. Pain doesn't negate strength :)  https://t.co/77TbkS2Djw", "@ReflectKnives You went solo because these moves weren't being made :D", 'hey my fav nirvana song is smells like teen spirit rip amy winehouse :-)))))', '#FollowFriday @CCIdeLYON @CCI_95 @CPNERI_ESIGROUP for being top engaged members in my community this week :)', "Let's go... I'll drive for you :p\n\n#traveling #traveler #yogyakarta #jeep #Indonesia #instamood… https://t.co/s7y4Ys5JeU", 'did we name the couple yet?? #TomHiddleston #ElizabethOlsen ?? #yaytheylookgreat :))', 'I love you all goodnight. Vid going up when I wake up you all with love this one :)', 'This weekend I am gonna shoot the lovely @NarakuBrock again &lt;3! Here a picture I made of her last time :D http://t.co/s3e2dmpt24', 'anyway :-)', 'Itty Bitty Teenie Bikini  :) http://t.co/A2oxW0ZI3g http://t.co/jn7KSfHwRc', 'I just joined the #HushedPinWithSammy Event :D Might get to Text with @SammyWilk for a day! Luv U @HushedApp http://t.co/czdow1i44W', 'Always so much fun when 4th hour gets together. :) \n\nEnding the night with ice cream and Xfiles. \n\nContent.', '@aangelayap easy :D', "@NTtownend yes, be surprised if we don't see a bit of rain today... :)", '@ReyesFraulein  follow @jnlazts &amp; http://t.co/RCvcYYO0Iq follow u back :)', 'To all @fatpunkstudio have a fabulous Friday and keep up the fantastic work!! :))', "@justinbieber can you please follow me @caitecat1209 ♡♡♡♡ please jb follow me I love you always and forever. I'm a belieber ♡♡♡♡ :) I love u", '#FollowFriday @DiploMix @CCI_entreprises @CCI_92 for being top influencers in my community this week :)', 'Morning all! :)', '@FranchiSeedsUK good to hear :)', "@LusciousLyndee1 Nighty night! Don't let the bed bugs bite :D", '@Bonsplansblog Very beautiful this bracelet! good idea :)', '@guywilliamsguy waiting for you at the foundry. Where you at?? :)', '@KalinWhite I like that game :)', "@suzannepanter @kevinbacon @katosman Ah! Now it makes sense... Didn't see the pic on my effing phone last night. Woot :) x", '@Derek_GTA Hi Derek, you could try using ParkShare in Gloucestershire http://t.co/qIF9AyAlkc :)', 'Aaaahhh man, this track is a traffic stress reliever. :)', '#FollowFriday @elevents2 @JoussotFrench_J @NYIBF for being top new followers in my community this week :)', "@El1neW How're you today my dear? :)", '@Jesutomisin I hear you guys want Arbeloa. :D', '@ShawnMendes turning 17 in 15 days...omg. at least we have only 3 years difference :)', '@matteomeacci Well, they say Europe is on the rise again, but I find that hard to believe :)', '@WforWoman #WSaleLove uncountable coz we love unlimited :)', 'Yes, of course :) #TeamPositive https://t.co/SaIX1VpFJF', 'yes i love :-) #AlDub', '@coffeebreak22 @LauRenArren @drparkave @JWKanyuira1969 @dheracing @RhoaChri @BarbaraBathurst @1cryingeye @willisteam :) ☕☕☕ Thank you Rita!', "@mikerobb Hi there, could you please DM us further info and we'd be happy to help! :)", '@24gooch on way my boy! :)', '@graphure I hope you will get a lot of nice gifts :D', 'Hi BAM ! @BarsAndMelody \nCan you follow my bestfriend @969Horan696 ? \nShe loves you a lot :) \nSee you in Warsaw &lt;3 \nLove you &lt;3 x40', '#FollowFriday @ACBM_SECEM @DCarsonCPA_NYC @PromosalonsInfo for being top supports in my community this week :)', 'So True!!  :)  https://t.co/N2ORwrOwhD', 'I added a video to a @YouTube playlist http://t.co/09GuSuMrNb im back on twitch and today it going to be league :) - 1 / 3', '@ZarlashtFaisal @Tabinda_Samar Sethi was HIGH ??? :)', '@IAm_Lennox exe skeem saam :)', 'These are the people who make me smile. :) @_pumpchkin_ @aka_pump @LilfrenchMsp @_Lishielou908_ http://t.co/iDdtACkA4K', '@CoSchedule Thanks for the invite. :)', '@SyedIHusain polite izzat :) \nwese does she trust him? khawateen k sath selfies say to mana kar deya :)', "Thank you @MovieTubePW that's my Friday evening sorted :-)", '@nova_caneeee you smart :)))', '@vaalthepal :-) nice hair tbh', '5 years :) https://t.co/hJEhDmxuu

In [69]:
print(stopwords.fileids())

['albanian', 'arabic', 'azerbaijani', 'basque', 'belarusian', 'bengali', 'catalan', 'chinese', 'danish', 'dutch', 'english', 'finnish', 'french', 'german', 'greek', 'hebrew', 'hinglish', 'hungarian', 'indonesian', 'italian', 'kazakh', 'nepali', 'norwegian', 'portuguese', 'romanian', 'russian', 'slovene', 'spanish', 'swedish', 'tajik', 'tamil', 'turkish']

In [ ]:
# Step 1: Apply the preprocessing pipeline to all tweets
preprocessed_tweets = [token for tweet in all_tweets for token in text_preprocessing_pipeline(tweet, "lemmatize")]

In [85]:
# Print a sample preprocessed tweet
print("Preprocessed Tweets Sample:", preprocessed_tweets)

Preprocessed Tweets Sample: ['followfriday', 'top', 'engaged', 'member', 'community', 'week', 'hey', 'james', 'odd', 'please', 'call', 'contact', 'centre', 'able', 'assist', 'many', 'thanks', 'despiteofficial', 'listen', 'last', 'night', 'bleed', 'amazing', 'track', 'scotland', 'congrats', 'yeaaaah', 'yippppy', 'accnt', 'verify', 'rqst', 'succeed', 'get', 'blue', 'tick', 'mark', 'fb', 'profile', 'day', 'bhaktisbanter', 'pallaviruhail', 'one', 'irresistible', 'flipkartfashionfriday', 'http', 'like', 'keep', 'lovely', 'customer', 'wait', 'long', 'hope', 'enjoy', 'happy', 'friday', 'lwwf', 'http', 'impatientraider', 'second', 'think', 'enough', 'time', 'dd', 'new', 'short', 'enter', 'system', 'sheep', 'must', 'buy', 'jgh', 'go', 'bayan', 'bye', 'act', 'mischievousness', 'call', 'etl', 'layer', 'warehouse', 'app', 'katamari', 'name', 'implies', 'p', 'followfriday', 'top', 'influencers', 'community', 'week', 'would', 'love', 'big', 'juicy', 'selfies', 'http', 'http', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'jjulieredburn', 'perfect', 'already', 'know', 'wait', 'great', 'new', 'opportunity', 'junior', 'triathletes', 'age', 'gatorade', 'series', 'get', 'entry', 'http', 'lay', 'greeting', 'card', 'range', 'print', 'today', 'love', 'job', 'friend', 'lunch', 'yummmm', 'nostalgia', 'tb', 'ku', 'rookiesenpai', 'arcadester', 'id', 'conflict', 'thanks', 'help', 'screenshot', 'work', 'hi', 'liv', 'hello', 'need', 'know', 'something', 'u', 'fm', 'twitter', 'sure', 'thing', 'dm', 'x', 'http', 'followfriday', 'top', 'new', 'follower', 'community', 'week', 'rossbreadmore', 'heard', 'four', 'season', 'pretty', 'dope', 'penthouse', 'obvs', 'gobigorgohome', 'fun', 'yeah', 'suppose', 'lol', 'chat', 'bite', 'x', 'hello', 'get', 'youth', 'job', 'opportunity', 'follow', 'gt', 'gt', 'tolajobjobs', 'see', 'year', 'bosslogic', 'amellywood', 'arrowwriters', 'thank', 'hope', 'rest', 'night', 'go', 'quickly', 'bed', 'get', 'music', 'fix', 'time', 'dream', 'spiritual', 'ritual', 'festival', 'népal', 'beginning', 'leave', 'see', 'http', 'hey', 'sarah', 'send', 'us', 'an', 'email', 'at', 'bitsy', 'and', 'we', 'help', 'you', 'asap', 'izzkamilhalda', 'lols', 'my', 'kik', 'kik', 'kikme', 'lgbt', 'tinder', 'nsfw', 'akua', 'cumshot', 'http', 'kalinwhite', 'come', 'house', 'effective', 'press', 'release', 'distribution', 'result', 'link', 'removed', 'pressrelease', 'newsdistribution', 'hi', 'bam', 'barsandmelody', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'lt', 'love', 'lt', 'everyone', 'watch', 'documentary', 'earthling', 'youtube', 'jamiefigsxx', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'followfriday', 'michelbauza', 'invataonline', 'top', 'support', 'community', 'week', 'buuuuuuuut', 'oh', 'well', 'leisuremarkltd', 'noshandquaff', 'aktarislam', 'keanebrands', 'heritagesilver', 'look', 'forward', 'visit', 'next', 'week', 'letsgetmessy', 'jo', 'sehunshinedaily', 'make', 'u', 'feel', 'well', 'never', 'see', 'anyone', 'kpop', 'flesh', 'cathstaincliffe', 'good', 'girl', 'best', 'wish', 'great', 'enough', 'reason', 'listen', 'one', 'epic', 'soundtrack', 'aquadesigngroup', 'thank', 'shout', 'great', 'friday', 'add', 'video', 'youtube', 'playlist', 'http', 'im', 'back', 'twitch', 'today', 'go', 'league', 'would', 'love', 'see', 'dear', 'jordan', 'wait', 'firdoz', 'visitjordan', 'dannyprol', 'oh', 'okay', 'thanks', 'sssniperwolf', 'like', 'fake', 'gameplays', 'haha', 'im', 'kid', 'im', 'kid', 'good', 'stuff', 'dennislami', 'yeah', 'exactly', 'new', 'product', 'line', 'etsy', 'shop', 'check', 'http', 'boxroomcrafts', 'peakyourmind', 'hope', 'vacation', 'go', 'great', 'groovinshawn', 'rechargeable', 'normally', 'come', 'charger', 'u', 'buy', 'followfriday', 'top', 'engaged', 'member', 'community', 'week', 'well', 'asleep', 'one', 'talk', 'sooo', 'someone', 'text', 'brynybrath', 'smallcappy', 'yes', 'suppose', 'bet', 'blue', 'fit', 'hearing', 'speech', 'today', 'pity', 'green', 'garden', 'midnight', 'sun', 'beautiful', 'canal', 'dasvidaniya', 'till', 'next', 'visit', 'keithrparsons', 'scout', 'sg', 'future', 'wlan', 'pro', 'conference', 'asia', 'wazimotometal', 'durooooooo', 'spigranty', 'good', 'u', 'good', 'change', 'lollipop', 'we', 'lt', 'u', 'nez', 'agnezmo', 'https', 'littlemix', 'follow', 'please', 'big', 'dream', 'elemaaan', 'oley', 'cowokaddict', 'mama', 'reason', 'stand', 'strong', 'macatangayapril', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'boukendreamer', 'oh', 'my', 'god', 'misty', 'my', 'baby', 'is', 'cute', 'd', 'bhaktisbanter', 'love', 'blue', 'flipkartfashionfriday', 'http', 'carcassdrop', 'woohoo', 'ca', 'wait', 'sign', 'yet', 'still', 'think', 'mka', 'liam', 'access', 'syuhxdxtengku', 'welcome', 'stats', 'day', 'arrive', 'new', 'follower', 'unfollowers', 'via', 'http', 'surprised', 'amazing', 'figure', 'followfriday', 'murtishaw', 'frtechstartups', 'top', 'influencers', 'community', 'week', 'happybirthdayemilybett', 'emilybett', 'wish', 'best', 'beautiful', 'sweet', 'talented', 'http', 'plan', 'day', 'drain', 'great', 'got', 'ta', 'love', 'timezones', 'p', 'parent', 'proud', 'lol', 'least', 'maybe', 'sometimes', 'get', 'happy', 'grade', 'al', 'http', 'grande', 'https', 'choose', 'follow', 'twitter', 'http', 'thanks', 'follow', 'syazwanzainal', 'sure', 'let', 'know', 'around', 'side', 'world', 'eh', 'u', 'take', 'care', 'followfriday', 'superninjaalan', 'top', 'new', 'follower', 'community', 'week', 'finally', 'fuck', 'weekend', 'real', 'lolesportspedia', 'thanks', 'hi', 'bam', 'barsandmelody', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'lt', 'love', 'lt', 'yes', 'join', 'hushedcallwithfraydoe', 'call', 'amp', 'gift', 'lt', 'get', 'ta', 'get', 'hushedapp', 'http', 'yaslarry', 'yeahhh', 'dm', 'amp', 'make', 'night', 'well', 'join', 'hushedpinwithsammy', 'event', 'might', 'get', 'text', 'sammywilk', 'day', 'luv', 'u', 'hushedapp', 'http', 'would', 'really', 'appreciate', 'share', 'video', 'around', 'http', 'hello', 'get', 'youth', 'job', 'opportunity', 'follow', 'gt', 'gt', 'tolajobjobs', 'tomparker', 'oh', 'wow', 'beautiful', 'tom', 'love', 'you', 'syreenanne', 'https', 'add', 'video', 'youtube', 'playlist', 'http', 'im', 'back', 'twitch', 'today', 'go', 'league', 'followfriday', 'americanograin', 'pecomep', 'apaulicand', 'top', 'support', 'community', 'week', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'gym', 'monday', 'ca', 'wait', 'like', 'harnilizalouis', 'hey', 'invite', 'join', 'scope', 'influencer', 'http', 'friend', 'know', 'wait', 'nude', 'jacobwhitesides', 'go', 'sleep', 'u', 'stats', 'day', 'arrive', 'new', 'follower', 'unfollowers', 'via', 'http', 'birthday', 'week', 'today', 'want', 'cool', 'axerade', 'haw', 'phela', 'look', 'like', 'mom', 'obviously', 'look', 'like', 'zaynmalik', 'prince', 'charm', 'stage', 'x', 'http', 'really', 'good', 'luck', 'stats', 'day', 'arrive', 'new', 'follower', 'unfollowers', 'via', 'http', 'followfriday', 'dcarsoncpa', 'top', 'engage', 'member', 'community', 'week', 'twentyonepilots', 'tyler', 'hipster', 'glass', 'martyrafenstein', 'hey', 'marty', 'glad', 'see', 'twitter', 'ukbusinesslunch', 'hi', 'join', 'today', 'lafitnessukhelp', 'do', 'thanks', 'already', 'afternoon', 'let', 'read', 'al', 'kahfi', 'day', 'finish', 'ohmyg', 'yaya', 'dub', 'mainedcm', 'im', 'do', 'stalk', 'ig', 'accnt', 'gondooo', 'moo', 'tologooo', 'haha', 'rozbabes', 'invite', 'become', 'scope', 'influencer', 'detail', 'http', 'followfriday', 'ngourd', 'locita', 'top', 'influencers', 'community', 'week', 'kevinthewhippet', 'spanielharry', 'thanks', 'zzz', 'xx', 'physiotherapy', 'friday', 'hashtag', 'today', 'custom', 'know', 'monica', 'miss', 'yeah', 'sound', 'good', 'good', 'morning', 'beautiful', 'take', 'hi', 'bam', 'barsandmelody', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'lt', 'love', 'lt', 'mandascapinello', 'oh', 'yeah', 'definitely', 'go', 'try', 'tonight', 'take', 'advice', 'treviso', 'morallosanthony', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'nikkieriozzi', 'hi', 'would', 'like', 'impastel', 'concert', 'let', 'know', 'city', 'country', 'start', 'work', 'thanks', 'fine', 'gorgeous', 'friday', 'friend', 'xo', 'http', 'oven', 'roast', 'garlic', 'olive', 'oil', 'sun', 'dry', 'tomato', 'dry', 'basil', 'century', 'tuna', 'http', 'hostmyoffice', 'nigelpwhittaker', 'lemezma', 'right', 'back', 'atchya', 'great', 'day', 'everyone', 'flashhayer', 'even', 'follow', 'back', 'future', 'almost', 'http', 'followfriday', 'michelploria', 'myfrenchcity', 'jasoncreation', 'top', 'new', 'follower', 'community', 'week', 'chance', 'mrclivec', 'pcdkirkwood', 'emwilliamscccu', 'laurargallagher', 'cheer', 'thatguycalledp', 'go', 'po', 'ice', 'cream', 'agree', 'spazzytsukihara', 'hehehehe', 'thats', 'point', 'p', 'kalinwhite', 'next', 'time', 'stay', 'home', 'thanks', 'followfriday', 'intlboost', 'top', 'support', 'community', 'week', 'stayfaboo', 'soon', 'promise', 'web', 'whatsapp', 'volta', 'funcionar', 'com', 'iphone', 'jailbroken', 'crustyolddeen', 'plan', 'watch', 'later', 'min', 'leia', 'appear', 'hologram', 'w', 'message', 'obi', 'wan', 'sits', 'w', 'luke', 'inter', 'ucl', 'arsenal', 'small', 'team', 'right', 'pass', 'dewsbury', 'railway', 'station', 'dew', 'nationalrailenq', 'dewsbury', 'west', 'yorkshire', 'http', 'clearlyarticle', 'smh', 'uptommosass', 'live', 'scotland', 'strange', 'imagine', 'megan', 'xx', 'bookmyshow', 'masaantoday', 'masaantoday', 'shweta', 'tripathi', 'masaantoday', 'masaantoday', 'wforwoman', 'w', 'kurtas', 'mom', 'half', 'number', 'wsalelove', 'ah', 'hello', 'back', 'larry', 'transworldbooks', 'https', 'anyway', 'friday', 'look', 'kinda', 'gooood', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'lol', 'well', 'life', 'thank', 'god', 'enn', 'http', 'ojbj', 'holmesjsamuel', 'surely', 'could', 'warmup', 'morning', 'come', 'bath', 'xx', 'dum', 'dum', 'andar', 'ram', 'sampath', 'sona', 'mohapatra', 'amp', 'samantha', 'edward', 'mein', 'tulane', 'razi', 'razi', 'wah', 'josh', 'http', 'justinbieber', 'always', 'smile', 'picture', 'arsenalnewsasit', 'thanks', 'time', 'right', 'perfect', 'timing', 'followfriday', 'izywaylesexpats', 'inxpresscoazur', 'top', 'engage', 'member', 'community', 'week', 'juleeyaanaa', 'know', 'giveitup', 'already', 'give', 'gas', 'subsidy', 'long', 'back', 'initiative', 'propose', 'feeling', 'delight', 'do', 'dayloladay', 'miss', 'yesterday', 'hi', 'bam', 'barsandmelody', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'lt', 'love', 'lt', 'lmaoo', 'best', 'song', 'ever', 'lt', 'shall', 'little', 'throwback', 'week', 'p', 'clazziebritchas', 'go', 'outlying', 'island', 'cheung', 'chau', 'mui', 'wo', 'totally', 'different', 'kfckitchentours', 'kitchen', 'clean', 'totally', 'amazed', 'cybelxxx', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'cusp', 'test', 'water', 'hope', 'reward', 'followfriday', 'broadcastbeat', 'insunwetrust', 'conseilsmkg', 'top', 'influencers', 'community', 'week', 'arummzz', 'let', 'go', 'drive', 'p', 'travel', 'traveler', 'yogyakarta', 'jeep', 'indonesia', 'http', 'anyone', 'wan', 'na', 'skype', 'agylyxa', 'may', 'look', 'bit', 'real', 'nice', 'friendly', 'girl', 'im', 'like', 'watch', 'concert', 'film', 'congratulation', 'winner', 'cheesydelights', 'contest', 'please', 'dm', 'u', 'address', 'contact', 'number', 'great', 'weekend', 'guy', 'https', 'followfriday', 'clararojasg', 'top', 'new', 'follower', 'community', 'week', 'puamagasiva', 'cool', 'see', 'film', 'today', 'check', 'email', 'marketing', 'http', 'wo', 'regret', 'buy', 'vineshpomal', 'lol', 'come', 'join', 'u', 'see', 'u', 'around', 'hour', 'u', 'leave', 'without', 'delay', 'actually', 'easy', 'like', 'must', 'station', 'guess', 'train', 'take', 'least', 'hour', 'shift', 'engine', 'etc', 'sunburn', 'peeling', 'visit', 'blog', 'http', 'thanks', 'tikosd', 'hi', 'would', 'like', 'impastel', 'concert', 'let', 'know', 'city', 'country', 'start', 'work', 'thanks', 'talk', 'help', 'cassthetrainer', 'huge', 'amp', 'warm', 'welcome', 'vodkablond', 'finally', 'complete', 'triangle', 'luciennediver', 'live', 'northern', 'ireland', 'sight', 'see', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'followfriday', 'tivipro', 'compexly', 'top', 'support', 'community', 'week', 'stats', 'day', 'arrive', 'new', 'follower', 'unfollowers', 'via', 'http', 'imraina', 'feel', 'smthng', 'smthng', 'fr', 'u', 'lol', 'wan', 'na', 'hug', 'u', 'xoxo', 'love', 'uu', 'jaann', 'take', 'care', 'lt', 'thanks', 'mom', 'thanks', 'topnewfollowers', 'bestofficpad', 'mrcfluegel', 'jeanmarcpn', 'happy', 'connect', 'mooseallain', 'meatbingo', 'wonderful', 'thing', 'make', 'feel', 'fluffy', 'inside', 'great', 'pirouette', 'moose', 'kristophcajon', 'trip', 'philly', 'december', 'love', 'come', 'dude', 'hi', 'bam', 'barsandmelody', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'lt', 'love', 'lt', 'question', 'flaw', 'pain', 'negate', 'strength', 'http', 'reflectknives', 'go', 'solo', 'move', 'make', 'hey', 'fav', 'nirvana', 'song', 'smell', 'like', 'teen', 'spirit', 'rip', 'amy', 'winehouse', 'followfriday', 'ccidelyon', 'top', 'engage', 'member', 'community', 'week', 'let', 'go', 'drive', 'you', 'p', 'traveling', 'traveler', 'yogyakarta', 'jeep', 'indonesia', 'https', 'name', 'couple', 'yet', 'tomhiddleston', 'elizabetholsen', 'yaytheylookgreat', 'love', 'goodnight', 'vid', 'go', 'wake', 'love', 'one', 'weekend', 'gon', 'na', 'shoot', 'lovely', 'narakubrock', 'lt', 'picture', 'make', 'last', 'time', 'http', 'anyway', 'itty', 'bitty', 'teenie', 'bikini', 'http', 'http', 'join', 'hushedpinwithsammy', 'event', 'might', 'get', 'text', 'sammywilk', 'day', 'luv', 'u', 'hushedapp', 'http', 'always', 'much', 'fun', 'hour', 'get', 'together', 'end', 'night', 'ice', 'cream', 'xfiles', 'content', 'aangelayap', 'easy', 'nttownend', 'yes', 'surprise', 'see', 'bit', 'rain', 'today', 'reyesfraulein', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'fatpunkstudio', 'fabulous', 'friday', 'keep', 'fantastic', 'work', 'justinbieber', 'please', 'follow', 'please', 'jb', 'follow', 'love', 'always', 'forever', 'belieber', 'love', 'u', 'followfriday', 'diplomix', 'top', 'influencers', 'community', 'week', 'morning', 'franchiseedsuk', 'good', 'hear', 'nighty', 'night', 'let', 'bed', 'bug', 'bite', 'bonsplansblog', 'beautiful', 'bracelet', 'good', 'idea', 'guywilliamsguy', 'wait', 'foundry', 'kalinwhite', 'like', 'game', 'suzannepanter', 'kevinbacon', 'katosman', 'ah', 'make', 'sense', 'see', 'pic', 'eff', 'phone', 'last', 'night', 'woot', 'x', 'hi', 'derek', 'could', 'try', 'use', 'parkshare', 'gloucestershire', 'http', 'aaaahhh', 'man', 'track', 'traffic', 'stress', 'reliever', 'followfriday', 'nyibf', 'top', 'new', 'follower', 'community', 'week', 'today', 'dear', 'jesutomisin', 'hear', 'guy', 'want', 'arbeloa', 'shawnmendes', 'turn', 'day', 'omg', 'least', 'year', 'difference', 'matteomeacci', 'well', 'say', 'europe', 'rise', 'find', 'hard', 'believe', 'wforwoman', 'wsalelove', 'uncountable', 'coz', 'love', 'unlimited', 'yes', 'course', 'teampositive', 'http', 'yes', 'love', 'aldub', 'laurenarren', 'drparkave', 'dheracing', 'rhoachri', 'barbarabathurst', 'willisteam', 'thank', 'rita', 'mikerobb', 'hi', 'could', 'please', 'dm', 'u', 'info', 'happy', 'help', 'way', 'boy', 'graphure', 'hope', 'get', 'lot', 'nice', 'gift', 'hi', 'bam', 'barsandmelody', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'lt', 'love', 'lt', 'followfriday', 'promosalonsinfo', 'top', 'support', 'community', 'week', 'so', 'true', 'https', 'add', 'video', 'youtube', 'playlist', 'http', 'im', 'back', 'twitch', 'today', 'go', 'league', 'zarlashtfaisal', 'sethi', 'was', 'high', 'exe', 'skeem', 'saam', 'people', 'make', 'smile', 'lilfrenchmsp', 'http', 'coschedule', 'thanks', 'invite', 'syedihusain', 'polite', 'izzat', 'wese', 'trust', 'khawateen', 'k', 'sath', 'selfies', 'say', 'mana', 'kar', 'deya', 'thank', 'movietubepw', 'friday', 'evening', 'sort', 'you', 'smart', 'vaalthepal', 'nice', 'hair', 'tbh', 'year', 'https', 'jacob', 'amp', 'g', 'upgrade', 'heydonworks', 'nice', 'tee', 'man', 'happy', 'family', 'vacation', 'pic', 'http', 'sleep', 'would', 'nice', 'read', 'beautiful', 'like', 'read', 'talk', 'one', 'person', 'two', 'conversation', 'skype', 'fun', 'soggystones', 'online', 'friday', 'http', 'followfriday', 'ccifccanada', 'adamevnmnt', 'top', 'engage', 'member', 'community', 'week', 'something', 'get', 'friday', 'great', 'start', 'great', 'day', 'mclaren', 'fridayfeeling', 'tgif', 'http', 'avinpera', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'square', 'enix', 'bissmillah', 'ya', 'allah', 'sephtonmark', 'training', 'socent', 'startup', 'tobaccodocklon', 'week', 'helpingb', 'love', 'drop', 'youre', 'arnd', 'town', 'hgvwolfie', 'basically', 'piss', 'cup', 'test', 'ellenrstewart', 'next', 'ionswitz', 'notch', 'also', 'twitter', 'terrible', 'complicated', 'discussion', 'snapchat', 'me', 'lynettelowe', 'snapchat', 'kikmenow', 'snapme', 'hot', 'snapchat', 'amazon', 'kikmeguys', 'http', 'look', 'forward', 'hour', 'shift', 'today', 'definately', 'agree', 'grow', 'sport', 'drop', 'email', 'detail', 'see', 'last', 'rt', 'rakyat', 'keep', 'visit', 'blog', 'read', 'write', 'http', 'ever', 'since', 'mention', 'fly', 'fish', 'day', 'get', 'follow', 'promote', 'post', 'lol', 'cyber', 'stalk', 'gurmeetramrahim', 'ourdaughtersourpride', 'mypapamypride', 'proud', 'papa', 'coach', 'imarpita', 'great', 'talk', 'never', 'see', 'positive', 'kha', 'u', 'could', 'also', 'mention', 'atleast', 'go', 'hi', 'bam', 'barsandmelody', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'lt', 'love', 'lt', 'omundson', 'mango', 'lassi', 'monty', 'marvellous', 'though', 'suspect', 'meant', 'followfriday', 'stayfanchemin', 'aandreup', 'top', 'influencers', 'community', 'week', 'haha', 'yes', 'hrs', 'time', 'come', 'touch', 'kepler', 'chalna', 'hai', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'allygrrdo', 'thankyou', 'pretty', 'pinkpeoniesblog', 'helloprettysa', 'definitely', 'hazel', 'food', 'market', 'brooklyn', 'pta', 'gt', 'gt', 'http', 'still', 'awake', 'joiredve', 'okayy', 'd', 'awww', 'thank', 'http', 'ha', 'surprise', 'least', 'okay', 'see', 'doc', 'afternoon', 'yorkshire', 'splendid', 'though', 'xx', 'jrturnerphoto', 'davidqueenan', 'jameslturnbull', 'spam', 'folder', 'wow', 'huge', 'amount', 'need', 'travel', 'nigeria', 'claim', 'perksofnialljh', 'rted', 'good', 'luck', 'legs', 'hurt', 'bad', 'get', 'mine', 'saturday', 'imafaithreyes', 'thaaanks', 'december', 'puhon', 'https', 'payumoney', 'true', 'change', 'tnc', 'without', 'prior', 'notification', 'could', 'use', 'last', 'night', 'http', 'probably', 'find', 'funny', 'aliyaskates', 'yoshihikomkm', 'fat', 'co', 'probably', 'ate', 'yuna', 'emmajaneparsons', 'curiousmindsnw', 'fun', 'tameside', 'hydrcted', 'charmingjedward', 'welcome', 'account', 'http', 'call', 'scouser', 'everything', 'hope', 'zoe', 'well', 'mate', 'right', 'literally', 'like', 'maybe', 'u', 'get', 'people', 'actually', 'know', 'studenttrip', 'rest', 'well', 'https', 'edgarslame', 'happy', 'birthday', 'edgar', 'hope', 'good', 'one', 'keep', 'update', 'travel', 'log', 'hello', 'd', 'vikkfollows', 'marreyjewana', 'bring', 'abes', 'stats', 'day', 'arrive', 'new', 'follower', 'unfollowers', 'via', 'http', 'someone', 'talk', 'to', 'never', 'ever', 'meet', 'bbcsport', 'come', 'man', 'follow', 'jnlazts', 'amp', 'http', 'follow', 'u', 'back', 'hi', 'bam', 'barsandmelody', 'follow', 'bestfriend', 'love', 'lot', 'see', 'warsaw', 'lt', 'love', 'lt', 'livelykaty', 'sigh', 'dreamily', 'pout', 'bath', 'eye', 'quacketyquack', 'happy', 'birthday', 'love', 'brianscrooks', 'burwellitltd', 'cheer', 'funny', 'happen', 'phil', 'wmfiredogs', 'call', 'amp', 'rodders', 'what', 'else', 'forkh', 'hi', 'may', 'like', 'play', 'new', 'gamejam', 'game', 'would', 'happy', 'http', 'great', 'irish', 'literature', 'really', 'inaccessible', 'u', 'without', 'irish', 'bhaktisbanter', 'pallaviruhail', 'yeah', 'fun

### **Exercise 10: Feature Extraction on Tweets**

Extract features from the preprocessed tweets using **Bag of Words** and **TF-IDF**. Store the results in ``X_bow`` and ``X_tfidf``, respectively.

In [87]:
# ------------------------------------------------------------------ #
#                      Création de Bag of Words                      #
# ------------------------------------------------------------------ #

from sklearn.feature_extraction.text import CountVectorizer

# Initialisation de CountVectorizer
bow_vect = CountVectorizer()

# Fit and transform the corpus into a BoW representation
X_bow = bow_vect.fit_transform(preprocessed_tweets)

print("BoW:\n", X_bow.toarray())
print("BoW Vocabulary:", bow_vect.get_feature_names_out())

# ------------------------------------------------------------------ #
#                               TF-IDF                               #
# ------------------------------------------------------------------ #

# Formulae : TF-IDF(mot, document) = TermFreq(mot, document) × InverseDocFreq(mot)

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import pandas as pd

# BoW to count the words
bow_vect2 = CountVectorizer(min_df=1) # min_df=1 : on garde tous les mots présents au moins 1 fois
term_freq_matrix = bow_vect2.fit_transform(preprocessed_tweets) # Matrix BoW

# Initialisation transformeur TF-IDF
X_tfidf = TfidfTransformer(norm="l2") # norm="l2" : normalise les vecteurs pour éviter que les longues phrases dominent
X_tfidf.fit(term_freq_matrix) # Fit du TF-IDF
tf_idf_matrix = X_tfidf.transform(term_freq_matrix) # Transforme la matrice de fréq en pondération TF-IDF

# Checks
print("TD-IDF: \n", tf_idf_matrix.todense()) # Affiche TF-IDF matrix
print("TD-IDF Vocabulary:", bow_vect2.vocabulary_, '\n') # Affiche le vocalubary généré avec index

# Data Viz => associe chaque mot à son poids IDF
df_idf = pd.DataFrame(X_tfidf.idf_, index=bow_vect2.get_feature_names_out(), columns=["idf_weights"])
df_idf.sort_values(by=['idf_weights']) # Tri fréquence croissant

BoW:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
BoW Vocabulary: ['aa' 'aaaaaaaaaaa' 'aaaaaaaaaaaaa' ... '에이핑크' '인피니트' 'ｍｅ']
TD-IDF:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

              idf_weights
http             4.622567
get              5.614844
follow           5.718743
love             5.863811
thanks           5.872286
...                   ...
lime            11.331871
limerickpost    11.331871
collins         11.331871
lils            11.331871
leak            11.331871

[14776 rows x 1 columns]

## **7. Conclusion**

In this lab, you explored a wide range of NLP techniques, from basic text preprocessing to advanced feature extraction and analysis. You also worked with a real-world dataset of tweets and applied your knowledge to preprocess and extract features for sentiment analysis.